version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: rexPexClient
      POSTGRES_PASSWORD: rexPexClient15&
      POSTGRES_DB: rexpref
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
